### ISSUE TITLE
Failed to process file on v7.34 (v7.28 works)

### ISSUE THREAD

**Issue by barratt** [StefanOltmann/oni-save-parser#1]
Hello!

Thank you for you work on this project, super cool. I've ran it successfully on older saves, however when uploading a new vanilla save I get the following:

```
Unexpected JSON token at offset 317: Expected string literal but 'null' literal was found at path: $.dlcId Use 'coerceInputValues = true' in 'Json {}' builder to coerce nulls to default values. JSON input: .....6d-b11b-51d7b1a260f5","dlcId":null,"dlcIds":[""]}
```

I am able to parse both using https://www.npmjs.com/package/oni-save-parser would be happy to discuss

Non-parseable save:
[0d570341-d2d9-4fa5-b10c-717319591dea.sav.zip](https://github.com/user-attachments/files/16329384/0d570341-d2d9-4fa5-b10c-717319591dea.sav.zip)

Parsable save:
[The Super Duper Laboratory.sav.zip](https://github.com/user-attachments/files/16329410/The.Super.Duper.Laboratory.sav.zip)

Thanks
Shaun

**Comment by StefanOltmann** [comment]
Hi Shaun,

thank you for reporting the bug and providing your files.

New files seem to have a slightly change around the DLC info structure as a save can now have multiple DLCs enabled. I fixed the code.

Kind regards,

Stefan
