### ISSUE TITLE
Unknown world: dlc2::worlds/MixingCeresAsteroid

### ISSUE THREAD

**Issue by maurodouglas** [StefanOltmann/oni-save-parser#2]
Hello, I'm trying to parse a save and is giving the error.

Unknown world: dlc2::worlds/MixingCeresAsteroid
[Radical Abode.zip](https://github.com/user-attachments/files/16854277/Radical.Abode.zip)

**Comment by StefanOltmann** [comment]
Yes, the logic needs to be updated for the most recent DLC frosty planet.

**Comment by StefanOltmann** [comment]
I don't think it makes much sense to update the save parser at this point. The main issue is that there is a lot of crucial information we currently can't extract from save files without a deeper understanding of the randomization process.

When I ported the save parser to Kotlin to create a ToolsNotIncluded replacement, I wasn't aware that we couldn't retrieve all the Geyser information from it as easily as a simple mod could.

https://github.com/barratt/mapsnotincluded.org is the way to go.
